env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  react/react-in-jsx-scope: 'off'
  react-hooks/rules-of-hooks: 'error'
  react-hooks/exhaustive-deps: 'warn'
  object-curly-spacing:
    - error
    - always
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always