export const GET_CLASSIFICATIONS = "GET_CLASSIFICATIONS";
export const SET_CLASSIFICATIONS = "SET_CLASSIFICATIONS";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
