export const GET_REQUESTS = "GET_REQUESTS";
export const SET_REQUESTS = "SET_REQUESTS";
export const GET_CLASSIFICATIONS = "GET_CLASSIFICATIONS";
export const SET_CLASSIFICATIONS = "SET_CLASSIFICATIONS";

