export const GET_REQUESTS = "GET_REQUESTS";
export const SET_REQUESTS = "SET_REQUESTS";
export const GET_CLASSIFICATIONS = "GET_CLASSIFICATIONS";
export const SET_CLASSIFICATIONS = "SET_CLASSIFICATIONS";
export const GET_REQUEST_STATUSES = "GET_REQUEST_STATUSES";
export const SET_REQUEST_STATUSES = "SET_REQUEST_STATUSES";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
