export const GET_PROJECTS = "GET_PROJECTS";
export const SET_PROJECTS = "SET_PROJECTS";

export const GET_CLIENTS = "GET_PROJECT_CLIENTS";
export const SET_CLIENTS = "SET_PROJECT_CLIENTS";

export const GET_OPERATORS = "GET_PROJECT_OPERATORS";
export const SET_OPERATORS = "SET_PROJECT_OPERATORS";
