name: Action on push to master branch

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Read package.json
        uses: tyankatsu0105/read-package-version-actions@v1
        id: package-version
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push current version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: MODE=prod
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/abv-crm-prod:v${{ steps.package-version.outputs.version }}
      - name: Build and push latest version
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: MODE=prod
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/abv-crm-prod:latest
